### PR TITLE
Update to Julia 0.6

### LINKED ISSUE #18: Warnings in 0.6
Deprecated syntax warnings when using NMF.
As of Julia 0.6

Edit: Originally noted long load time. This is negligible once I examined further. 

```
WARNING: deprecated syntax "abstract NMFUpdater{T}" at /home/jsybran/.julia/v0.6/NMF/src/common.jl:39.
Use "abstract type NMFUpdater{T} end" instead.

WARNING: deprecated syntax "inner constructor Result(...) around /home/jsybran/.julia/v0.6/NMF/src/common.jl:29".
Use "Result{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor MultUpdate(...) around /home/jsybran/.julia/v0.6/NMF/src/multupd.jl:22".
Use "MultUpdate{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor MultUpdMSE_State(...) around /home/jsybran/.julia/v0.6/NMF/src/multupd.jl:54".
Use "MultUpdMSE_State{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor MultUpdDiv_State(...) around /home/jsybran/.julia/v0.6/NMF/src/multupd.jl:111".
Use "MultUpdDiv_State{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor ProjectedALS(...) around /home/jsybran/.julia/v0.6/NMF/src/projals.jl:31".
Use "ProjectedALS{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor ProjectedALSUpd_State(...) around /home/jsybran/.julia/v0.6/NMF/src/projals.jl:52".
Use "ProjectedALSUpd_State{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor ALSGradUpdH_State(...) around /home/jsybran/.julia/v0.6/NMF/src/alspgrad.jl:51".
Use "ALSGradUpdH_State{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor ALSGradUpdW_State(...) around /home/jsybran/.julia/v0.6/NMF/src/alspgrad.jl:212".
Use "ALSGradUpdW_State{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor ALSPGrad(...) around /home/jsybran/.julia/v0.6/NMF/src/alspgrad.jl:376".
Use "ALSPGrad{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor ALSPGradUpd_State(...) around /home/jsybran/.julia/v0.6/NMF/src/alspgrad.jl:399".
Use "ALSPGradUpd_State{T}(...) where T" instead.

```

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #18.

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like there are still some deprecation warnings that should be addressed before this is merged. Not sure what's up with the error yet.

**Comment by ararslan** [comment]
Okay cool, this is good on deprecations now. Still don't know what the issue is with the error but we can figure that out later.

**Comment by ararslan** [comment]
Cool, tests are now passing on 0.6 and the error about alpha being infinite is only happening on 0.7.

**Comment by ararslan** [comment]
I think I'm done here. Want to have another look @andreasnoack?

**Comment by andreasnoack** [comment]
I still see the issue here https://travis-ci.org/JuliaStats/NMF.jl/jobs/298202149

**Comment by ararslan** [comment]
Whoa, weird--the push build failed on 0.6 and the PR build passed on 0.6.

**Comment by ararslan** [comment]
The push build was also not retriggered on close/open. What in the world is going on...

**Comment by ararslan** [comment]
Okay I restarted the push build manually and now the 0.6 tests are passing there too.

**Comment by ararslan** [comment]
Oddly enough the tests also passed on 0.7 in that build. I wonder if the issue is because we're using random matrices in the tests.

**Comment by ararslan** [comment]
As an aside, the commits here were a little messy; probably should have been squash-merged.

**Pull request merged**
