### PR TITLE
Add greedy coordinate descent algorithm

### PR DESCRIPTION
**Pull request by tsano430**
I implemented a greedy coordinate descent algorithm [1] for MSE-based NMF and confirmed that the algorithm works fast and stable for both dense and sparse matrices. The benchmark is [here][bench]. Furthermore, I unified the definition of the objective function for each algorithm. 

[1] Cho-Jui Hsieh and Inderjit S. Dhillon. "Fast coordinate descent methods with variable selection for non-negative matrix factorization." In Proceedings of the 17th ACM SIGKDD International Conference on Knowledge Discovery and Data Mining, pp. 1064–1072, 2011.

[bench]: https://gist.github.com/tsano430/68de73c79543971a649177bd8322d53a

### CODE REVIEW

**Comment by tsano430** [comment]
As far as I know, this is the fastest algorithm for MSE-based NMF. I think this pull request is worth being merged. Please confirm the above.

**Comment by tsano430** [comment]
@andreasnoack I squashed my messy commits together into one commit. I'm sorry for the inconvenience.

**Comment by andreasnoack** [comment]
Thanks for the contribution

**Comment by tsano430** [comment]
@andreasnoack Thank you for merging this pull request!

**Pull request merged**
