### PR TITLE
split nndsvd function

### PR DESCRIPTION
**Pull request by youdongguo**

### CODE REVIEW

**Comment by ararslan** [comment]
Hi @youdongguo, thanks for the contribution! Could you provide some background for this change, as in your motivation for it and what problem(s) it aims to solve?

**Comment by youdongguo** [comment]
> Hi @youdongguo, thanks for the contribution! Could you provide some background for this change, as in your motivation for it and what problem(s) it aims to solve?


> Hi I am still working on the change and made the pull request too early. Sorry about that.

**Comment by ararslan** [comment]
No worries at all! Also FYI in case you didn't already know, GitHub allows you to open draft pull requests, which are unable to be merged until they're explicitly switched out of draft mode. That provides a signal to folks that it's not yet ready for review, so it's useful if you're still working on something.

**Comment by youdongguo** [comment]
> No worries at all! Also FYI in case you didn't already know, GitHub allows you to open draft pull requests, which are unable to be merged until they're explicitly switched out of draft mode. That provides a signal to folks that it's not yet ready for review, so it's useful if you're still working on something.

Thanks very much for the information.

**Pull request closed without merging**
