### PR TITLE
Added spa algorithm and tests

### PR DESCRIPTION
**Pull request by silenj**
Added algorithm spa, added test routines and made package compatible with julia v0.6. Changes made it incompatible with v0.5.

### CODE REVIEW

**Comment by tsano430** [comment]
@ararslan, could I ask what is blocking from reviewing this PR based on #12? I think it is worth merging the Successive Projection Algorithm (SPA) for separable NMF into NMF.jl. Thanks.

**Comment by ararslan** [comment]
Neither this PR nor #12 are able to be merged due to conflicts.

**Comment by tsano430** [comment]
@ararslan Thank you for your reply!

@silenj Could you please resolve the conflicts if you're still interested in this PR? If you're not interested in it now, may I create a new PR based on it?

**Comment by silenj** [comment]
Thank you, please go ahead. I have not used or looked at the package for
ages.

rgds Johan

Den ons 17 feb. 2021 02:13Takehiro Sano <notifications@github.com> skrev:

**Comment by silenj** [comment]
I can take a look but only next weekend.

Rgds Johan

Den ons 17 feb. 2021 02:13Takehiro Sano <notifications@github.com> skrev:

**Comment by tsano430** [comment]
Thank you for letting me know. I'll work on it.

**Comment by tsano430** [comment]
@silenj PR #50 was merged. Ok to close?

**Comment by silenj** [comment]
Fine with me.

rgds Johan


Den mån 8 mars 2021 15:58Takehiro Sano <notifications@github.com> skrev:

**Pull request closed without merging**
