### PR TITLE
nndsvd: allow initialization with externally-supplied factorization

### PR DESCRIPTION
**Pull request by timholy**
rsvd is fast, but it's also noisy (i.e., not deterministic) and of lower quality than exact SVD. Particularly if you have already computed the SVD for other reasons, it's nice to be able to use it in initializing via nndsvd.

This starts with the abandoned #68 and brings it over the finish line. CC @youdongguo.

This will not pass tests on its own, but if you merge #69 first, close this, and then reopen, it should pass.

There are quite a few trailing-whitespace changes; you can change the settings (the "gear" icon under `Files changed`) to omit those for easier review.

### CODE REVIEW

**Comment by ararslan** [comment]
Any idea what's going on with this test (added in this PR) only on Linux with 1.8?
```
Test Failed at /home/runner/work/NMF.jl/NMF.jl/test/initialization.jl:48
  Expression: norm(X - W2 * H2) < norm(X - W1 * H1)
   Evaluated: 2.0457485837143 < 2.039189688675492
```

**Comment by timholy** [comment]
This time, they all passed.

What's interesting is that the random seed isn't set before construction of `X` for `Float64`; it gets set during the `Float64` tests and then makes the `X` for `Float32` deterministic, but `Float64` is not deterministic. I think before merging this it might make sense to standardize all this. Since we set the seed in `@testset`s, I think it's high time to transition the tests to `@testset`s. I'll do that first before merging this.

@ararslan, are you otherwise OK with it?

**Comment by ararslan** [comment]
> @ararslan, are you otherwise OK with it?

Sure am!

**Comment by timholy** [comment]
Weird. There are non-reproducible failures. Did we just get lucky with #72?

**Pull request merged**
