### PR TITLE
Remove many type annotations and generalize acceptable types

### PR DESCRIPTION
**Pull request by timholy**
This supports various element types (e.g., Float32). It also supports more general matrix-like objects (not necessarily even `AbstractArray`s, as long as they support operations like size, eltype, and multiplication).

### CODE REVIEW

**Comment by timholy** [comment]
OK, I hadn't noticed this had failed its Travis tests for `juliareleases` (but not `julianightlies`). It turns out to have been due to differences in the random numbers generated by the two versions of julia, and was only triggered via the increased number of tests in this PR. In other words, the first commit in this PR revealed a long-standing convergence bug. This bug appears to have been fixed in second commit.

FYI I don't have commit privileges, so I'm relying on someone from JuliaStats to review and potentially merge.

**Comment by lindahua** [comment]
Thanks @timholy 
I haven't got time taking care of Julia repos lately.

**Comment by timholy** [comment]
Not a problem, and welcome back!

On the longer-term horizon, internally I have an implementation of the HALS algorithm, which has been [shown](http://fodava.gatech.edu/sites/default/files/FODAVA-12-71.pdf) to be very competitive. It's quite far down on my priority list right now, but eventually it would be good to release this publicly. I foresee a couple of challenges integrating it here:

- HALS never needs to compute `sumabs2(A-W*H)`, and indeed computing that quantity even once (not once per iteration, but simply...once) can be a bottleneck when `A` is big but the number of components is tiny. However, `Result` has the field `objvalue`, which basically forces one to compute this quantity.
- I needed a fancy feature: masking. The idea is to supply `Wmask` and `Hmask`, and `W[i,j]` can be nonzero only if `Wmask[i,j] == true`. The HALS algorithm is so simple that it's easy to implement such extensions, but this poses a challenge for attempts to provide a common API to many algorithms.

Anyway, to take advantage of your reappearance I thought I'd raise these issues now, but keep in mind it could be weeks or months before I'm ready to submit this work.

**Comment by lindahua** [comment]
@timholy The paper looks interesting. I am looking forward to your implementation.

As I am developing a new course this semester, I won't be able to do a lot of coding before the end of this term at May. Hopefully, I can resume my contributions a bit after that.

**Comment by timholy** [comment]
Understood. It may well be summer anyway.

**Pull request merged**
