### PR TITLE
Updates for 1.0

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by bicycle1885** [comment]
Any updates here 😃? I'd like to use this in Julia 1.0.

**Comment by ararslan** [comment]
Interesting... We're getting this on 0.7 and nightly, but not 1.0.
```
Running tests:
* utils.jl ...
* initialization.jl ...
* alspgrad.jl ...
ERROR: LoadError: LoadError: α is not finite
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./printf.jl:160 [inlined]
 [3] _alspgrad_updatew!(::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::NMF.ALSGradUpdW_State{Float64}, ::Int64, ::Int64, ::Float64, ::Float64, ::Float64, ::Bool) at /home/travis/build/JuliaStats/NMF.jl/src/alspgrad.jl:271
...
```

**Comment by ararslan** [comment]
Hm, I can't reproduce the 0.7 failure locally.

**Comment by ararslan** [comment]
Oh, different combinations of versions are passing and failing across builds. Looks like it's because we're relying on randomly generated matrices in the tests. Doesn't seem to matter that the random seed is set, which is odd.

**Comment by haberdashPI** [comment]
Just wanted to note that I've been using this branch of NMF.jl for some time now in a project and have had no issues so far. At least for the data I'm using this appears to give equivalent results to the 0.6 code.

**Comment by ararslan** [comment]
This has been open a long time and actually fully works, the problem is just with tests relying on randomly generated matrices. So I think this should be fine to merge.

**Pull request merged**
